# Main website
server {
    listen 80;
    server_name yoav.ch;

    root /var/www/website;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# Music subdomain
server {
    listen 80;
    server_name schmoundcloud.yoav.ch;

    root /var/www/schmoundcloud;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /music/ {
    proxy_pass http://music-site:3000/music/;
    expires 30d;
    }

    location /waveforms/ {
        proxy_pass http://music-site:3000/waveforms/;
        expires 30d;
    }
}
