# Main website
server {
    listen 80;
    server_name yoav.ch;

    root /var/www/website;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# Music subdomain
server {
    listen 80;
    server_name schmoundcloud.yoav.ch;

    root /var/www/schmoundcloud;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
