tunnel: mysite
credentials-file: /etc/cloudflared/mysite.json

ingress:
  - hostname: yoav.ch
    service: http://nginx:80

  - hostname: info.yoav.ch
    service: http://nginx:80

  - hostname: schmoundcloud.yoav.ch
    service: http://nginx:80

  - service: http_status:404
